# Generated by Django 4.0.1 on 2022-01-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesbackend', '0002_rename_rate_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='averageRating',
            new_name='totalRating',
        ),
    ]
