# Generated by Django 4.0.1 on 2022-01-30 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviesbackend', '0003_rename_averagerating_movie_totalrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='totalRating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='moviesbackend.movie'),
        ),
    ]
